Add back vendor.display.config@1.0
Needed to prevent gcam from crashing in some scenarios:
Error: dlopen failed: library "vendor.display.config@1.0.so" not found: needed by /product/lib64/libsecureuisvc_jni.so in namespace classloader-namespace-shared

Signed-off-by: spezi77 <spezi7713@gmx.net>